DEFAULT_CRYPTO_SYMBOLS = [
    "BTCUSDT",
    "ETHUSDT",
    "SOLUSDT",
    "BNBUSDT",
    "XRPUSDT",
    "DOGEUSDT",
]
DEFAULT_STOCK_SYMBOLS = [
    "AAPL",
    "MSFT",
    "NVDA",
    "AMZN",
    "GOOGL",
    "TSLA",
]

BINANCE_WS_BASE = "wss://stream.binance.com:9443/stream"
BINANCE_REST_BASE = "https://api.binance.com/api/v3"
FINVIZ_CRYPTO_NEWS_URL = "https://finviz.com/news.ashx?v=5"
FINVIZ_STOCKS_NEWS_URL = "https://finviz.com/news.ashx?v=3"
FINVIZ_ECONOMY_NEWS_URL = "https://finviz.com/news.ashx?v=4"
FINVIZ_TECH_NEWS_URL = "https://finviz.com/news.ashx?v=6"
FINVIZ_GENERAL_NEWS_URL = "https://finviz.com/news.ashx"
RECONNECT_SECONDS = 2
MAX_POINTS = 240
MAX_EVENTS = 300
NEWS_REFRESH_SECONDS = 600
NEWS_MAX_ITEMS = 21
NEWS_GROUP_SIZE = 7
NEWS_GROUP_ROTATE_SECONDS = 10
STOCK_GROUP_ROTATE_SECONDS = 10
STOCKS_REFRESH_SECONDS = 600
CALENDAR_REFRESH_SECONDS = 3600
CALENDAR_HORIZON_DAYS = 15
CALENDAR_SOON_HOURS = 8
# Faster boot defaults; chart modal will complete history on-demand.
INITIAL_HISTORY_POINTS = 80
INITIAL_CANDLE_LIMIT = 32
CHART_HISTORY_POINTS = 240
CACHE_TTL_SECONDS = 900
NAME_CACHE_TTL_SECONDS = 86400
DESCRIPTION_CACHE_TTL_SECONDS = 7 * 86400
STARTUP_IO_CONCURRENCY = 6
DEFAULT_LANGUAGE = "es"

# News metadata palette (configurable system colors).
NEWS_META_BRACKET_COLOR = "#6f8aa8"
NEWS_META_SOURCE_COLOR = "#8ad9ff"
NEWS_META_AGE_NOW_COLOR = "#00ffae"
NEWS_META_AGE_RECENT_COLOR = "#ffcf5c"
NEWS_META_AGE_OLD_COLOR = "#7aa3c5"
NEWS_META_FIRE_COLOR = "#ff7a00"
