DEFAULT_CRYPTO_SYMBOLS = [
    "BTCUSDT",
    "ETHUSDT",
    "SOLUSDT",
    "BNBUSDT",
    "XRPUSDT",
    "DOGEUSDT",
]
DEFAULT_STOCK_SYMBOLS = [
    "AAPL",
    "MSFT",
    "NVDA",
    "AMZN",
    "GOOGL",
    "TSLA",
]

BINANCE_WS_BASE = "wss://stream.binance.com:9443/stream"
BINANCE_REST_BASE = "https://api.binance.com/api/v3"
FINVIZ_CRYPTO_NEWS_URL = "https://finviz.com/news.ashx?v=5"
RECONNECT_SECONDS = 2
MAX_POINTS = 240
MAX_EVENTS = 300
NEWS_REFRESH_SECONDS = 600
NEWS_MAX_ITEMS = 12
STOCKS_REFRESH_SECONDS = 600
INITIAL_HISTORY_POINTS = 240
INITIAL_CANDLE_LIMIT = 96
